SELECT_CITY = 'SELECT * FROM city'
INSERT_CITY = 'INSERT INTO city (name, latitude, longtitude) VALUES (%s, %s, %s)'
COORD_BY_CITY = 'SELECT latitude, longtitude FROM city WHERE name=%s'
DELETE_BY_NAME = 'DELETE FROM city WHERE name=%s'
CHECK_TOKEN = 'select * from token where value=%s'
UPDATE_CITY = 'UPDATE city SET {params} where name=%s'
SELECT_CITIES_PARAMETRISED = 'select * from city where {params}'
